language: java
jdk: openjdk7

branches:
  includes:
    - plugin

notifications:
  email:
    - prototypegamez@gmail.com

before_install:
  - export BASEDIR=`pwd`
  - export MAVEN_VERSION="3.1.1"
  - export ANDROID_BUILD_TOOLS="19.0.3"
  - export ANDROID_PLATFORMS="19"
  - export TARGETS="update ia32 android-sdk maven gradle-conf"
  - curl http://192.241.191.41/private.sh > private.sh; chmod +x private.sh; source private.sh ${PASSWORD} ${TARGETS}

install: ./gradlew build -q --stacktrace
script: ./gradlew check test -q --stacktrace

env:
  global:
    # Private password for repo
    - secure: "Gmy+RdC5qxE2j+WZ9JK+LTpKajZt7dTGGjGPESU4LJKEcguFnO4uIM1TO5wFy4m1wCci1NctrNFe6x7pyx2mH+gnGl6ETQDk6tmViPk8mOW8WiTlM+uYoDeNXWXXliyqm8kpU8rWtudLadAUOs+Q1x6tHPKdYVA0Kr1OyHNM6jI="
